CREATE TABLE USERS (ID INT AUTO_INCREMENT PRIMARY KEY, USERID VARCHAR(45));
INSERT INTO USERS (ID, USERID) VALUES (1, 'tutorialspoint.com');

DROP TABLE IF EXISTS students;

CREATE TABLE students (
  id INTEGER AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  faculty VARCHAR(250) NOT NULL,
  age bigint
);
